language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t yaser/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yaser/react-test npm test

after_success:
  - docker build -t yaserhesham/multi-client ./client
  - docker build -t yaserhesham/multi-nginx ./nginx
  - docker build -t yaserhesham/multi-server ./server
  - docker build -t yaserhesham/multi-worker ./worker
  #pushing to docker hub
  #1- logging in to docker hub
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  #2- push the imgaes
  - docker push yaserhesham/multi-client 
  - docker push yaserhesham/multi-nginx 
  - docker push yaserhesham/multi-server 
  - docker push yaserhesham/multi-worker 

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-multi'
  env: 'Dockermulti-env'
  bucket_name: 'elasticbeanstalk-us-east-1-809629861212'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

