language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t yaser/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yaser/react-test npm test

after_success:
  - docker build -t yaser/multi-client ./client
  - docker build -t yaser/multi-nginx ./nginx
  - docker build -t yaser/multi-server ./server
  - docker build -t yaser/multi-worker ./worker